Vagrant.configure("2") do |config|
  config.vm.box = "rhel8"
  config.vm.hostname = "rhel8"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
end
