$ocClusterUp = <<SCRIPT
oc cluster up --public-hostname 192.168.3.100
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "twistedvines/openshift"
  config.vm.box_version = "1.0.0"
  config.vm.hostname = "openshift"
  config.vm.network "private_network", ip: "192.168.3.100"
  config.vm.provision "shell", inline: $ocClusterUp

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
end
